name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  IMAGE_NAME: "heart_disease_pred"
  IMAGE_TAG: "latest:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
      
    - name: Run container
      run: 
          - docker run -d -p 8080:8080 --name ${{ env.IMAGE_NAME }}
  
    - name: Display running containers
      run: 
         - docker ps -a
